// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FireForce.Data;

#nullable disable

namespace FireForce.Core.Data.Migrations
{
    [DbContext(typeof(BomberosDbContext))]
    [Migration("20260119172249_FixNulleablesSocios")]
    partial class FixNulleablesSocios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Data.Models.Grupos.Brigadas.Bombero_Brigada", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("BrigadaId")
                        .HasColumnType("int");

                    b.HasKey("PersonaId", "BrigadaId");

                    b.HasIndex("BrigadaId");

                    b.ToTable("bombero_brigada");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Brigadas.Brigada", b =>
                {
                    b.Property<int>("BrigadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrigadaId"));

                    b.Property<int>("EncargadoPersonaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreBrigada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("BrigadaId");

                    b.HasIndex("EncargadoPersonaId");

                    b.HasIndex("NombreBrigada")
                        .IsUnique();

                    b.ToTable("Brigadas");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.Bombero_Dependencia", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("int");

                    b.HasKey("PersonaId", "DependenciaId");

                    b.HasIndex("DependenciaId");

                    b.ToTable("bombero_dependencia");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.Comunicaciones.Comunicacion", b =>
                {
                    b.Property<int>("ComunicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComunicacionId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("NroEquipo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NroSerie")
                        .HasColumnType("longtext");

                    b.HasKey("ComunicacionId");

                    b.HasIndex("NroEquipo")
                        .IsUnique();

                    b.ToTable("Comunicacion");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.Dependencia", b =>
                {
                    b.Property<int>("DependenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DependenciaId"));

                    b.Property<int>("EncargadoPersonaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreDependencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DependenciaId");

                    b.HasIndex("EncargadoPersonaId");

                    b.ToTable("Dependencias");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.EquiposAutonomos.EquipoAutonomo", b =>
                {
                    b.Property<int>("EquipoAutonomoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipoAutonomoId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVencimientoPruebaHidraulica")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("NroSerie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NroTubo")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMaterial")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimaFechaPruebaHidraulica")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EquipoAutonomoId");

                    b.ToTable("EquiposAutonomos");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.EquiposAutonomos.Movimiento_EquipoAutonomo", b =>
                {
                    b.Property<int>("Movimiento_EquipoAutonomoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Movimiento_EquipoAutonomoId"));

                    b.Property<string>("AgenteAnterior")
                        .HasColumnType("longtext");

                    b.Property<int?>("DependenciaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoAutonomoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OtroDestino")
                        .HasColumnType("longtext");

                    b.Property<int?>("VehiculoDestinoId")
                        .HasColumnType("int");

                    b.HasKey("Movimiento_EquipoAutonomoId");

                    b.HasIndex("DependenciaDestinoId");

                    b.HasIndex("EncargadoId");

                    b.HasIndex("EquipoAutonomoId");

                    b.HasIndex("VehiculoDestinoId");

                    b.ToTable("MovimientosEquiposAutonomos");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.FuerzasIntervinientes.FuerzaInterviniente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreFuerza")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fuerzas");
                });

            modelBuilder.Entity("Core.Data.Models.Imagenes.Imagen", b =>
                {
                    b.Property<int>("ImagenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImagenId"));

                    b.Property<byte[]>("DatosImagen")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("NombreImagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("TipoImagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ImagenId");

                    b.ToTable("Imagen");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Data.Models.Objetos.Componentes.MovimientoMaterial", b =>
                {
                    b.Property<int>("MovimientoMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MovimientoMaterialId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("DestinoBomberoPersonaId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinoMovilVehiculoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MaterialesMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("esComisionDirectiva")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MovimientoMaterialId");

                    b.HasIndex("DestinoBomberoPersonaId");

                    b.HasIndex("DestinoMovilVehiculoId");

                    b.HasIndex("MaterialesMaterialId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Core.Data.Models.Objetos.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rubro")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Core.Data.Models.Otros.Partes.ParteVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "Tipo")
                        .IsUnique();

                    b.ToTable("PartesVehiculo");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Damnificado_Salida", b =>
                {
                    b.Property<int>("Damnificado_SalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Damnificado_SalidaId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Destino")
                        .HasColumnType("longtext");

                    b.Property<int?>("Documento")
                        .HasColumnType("int");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<int?>("FuerzaIntervinienteId")
                        .HasColumnType("int");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Damnificado_SalidaId");

                    b.HasIndex("FuerzaIntervinienteId");

                    b.HasIndex("SalidaId");

                    b.ToTable("Damnificados");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonaId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Documento")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Residencia")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("PersonaId");

                    b.ToTable("Persona");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Componentes.AscensoBombero", b =>
                {
                    b.Property<int>("AscensoBomberoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AscensoBomberoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("FechaAscenso")
                        .HasColumnType("date");

                    b.Property<string>("GradoAntiguo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GradoAscenso")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumeroActa")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLibero")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("AscensoBomberoId");

                    b.HasIndex("PersonaId");

                    b.ToTable("AscensoBomberos");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Componentes.Contacto", b =>
                {
                    b.Property<int>("ContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContactoId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TelefonoLaboral")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ContactoId");

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Componentes.Licencia", b =>
                {
                    b.Property<int>("LicenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LicenciaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Desde")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EstadoLicencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Hasta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("RazonRechazo")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoLicencia")
                        .HasColumnType("int");

                    b.HasKey("LicenciaId");

                    b.HasIndex("PersonalId");

                    b.ToTable("Licencias");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Componentes.Sancion", b =>
                {
                    b.Property<int>("SancionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SancionId"));

                    b.Property<string>("DescripcionSancion")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SacionArea")
                        .HasColumnType("int");

                    b.Property<string>("TipoSancion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SancionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Sanciones");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.BomberoSalida", b =>
                {
                    b.Property<int>("BomberoSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BomberoSalidaId"));

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MovilId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("BomberoSalidaId");

                    b.HasIndex("MovilId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("BomberosSalida");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.FuerzaInterviniente_Salida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EncargadoApellidoyNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FuerzaIntervinienteId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroUnidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuerzaIntervinienteId");

                    b.HasIndex("SalidaId");

                    b.ToTable("fuerzaInterviniente_Salidas");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.Movil_Salida", b =>
                {
                    b.Property<int>("Movil_SalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Movil_SalidaId"));

                    b.Property<string>("CantidadLitros")
                        .HasColumnType("longtext");

                    b.Property<bool>("CargoCombustible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DotacionSalida")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaFactura")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KmLlegada")
                        .HasColumnType("int");

                    b.Property<int>("MovilId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("QuienLleno")
                        .HasColumnType("longtext");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoQuienLleno")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoConbustible")
                        .HasColumnType("longtext");

                    b.HasKey("Movil_SalidaId");

                    b.HasIndex("MovilId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("MovilesSalida");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.OcupanteVehiculo", b =>
                {
                    b.Property<int>("OcupanteVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OcupanteVehiculoId"));

                    b.Property<int>("DamnificadoSalidaId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoAfectadoId")
                        .HasColumnType("int");

                    b.HasKey("OcupanteVehiculoId");

                    b.HasIndex("DamnificadoSalidaId")
                        .IsUnique();

                    b.HasIndex("VehiculoAfectadoId");

                    b.ToTable("OcupantesVehiculos");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.Seguro", b =>
                {
                    b.Property<int>("SeguroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SeguroId"));

                    b.Property<string>("CompañiaAseguradora")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("SeguroId");

                    b.ToTable("Seguro");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.Property<int>("SalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SalidaId"));

                    b.Property<int>("AnioNumeroParte")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoSolicitante")
                        .HasColumnType("longtext");

                    b.Property<string>("Depto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DniSolicitante")
                        .HasColumnType("longtext");

                    b.Property<int>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("NombreSolicitante")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreYApellidoReceptor")
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroParte")
                        .HasColumnType("int");

                    b.Property<string>("PisoNumero")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuienLlenoId")
                        .HasColumnType("int");

                    b.Property<int?>("SeguroId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoSolicitante")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoEmergencia")
                        .HasColumnType("int");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("TipoZona")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SalidaId");

                    b.HasIndex("EncargadoId");

                    b.HasIndex("QuienLlenoId");

                    b.HasIndex("SeguroId")
                        .IsUnique();

                    b.ToTable("Salidas");

                    b.HasDiscriminator<int>("TipoEmergencia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Componentes.MovimientoSocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("HistorialSocios");

                    b.HasDiscriminator().HasValue("MovimientoSocio");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Componentes.Pagos.PagoSocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfirmadoPorPersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaConfirmadoORechazado")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Monto")
                        .HasColumnType("double");

                    b.Property<string>("RazonRechazo")
                        .HasColumnType("longtext");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmadoPorPersonaId");

                    b.HasIndex("SocioId");

                    b.ToTable("PagoSocio");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionSecundaria")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentoOCUIT")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EstadoSocio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaIngresoSistemaNuevo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormaPago")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenciaDePago")
                        .HasColumnType("int");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double");

                    b.Property<double?>("LatitudSecundaria")
                        .HasColumnType("double");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double");

                    b.Property<double?>("LongitudSecundaria")
                        .HasColumnType("double");

                    b.Property<double>("MontoCuota")
                        .HasColumnType("double");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NotaAdicional")
                        .HasColumnType("longtext");

                    b.Property<int>("NroSocio")
                        .HasColumnType("int");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("Zona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NroSocio")
                        .IsUnique();

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Flota.EmbarcacionAfectada", b =>
                {
                    b.Property<int>("EmbarcacionAfectadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmbarcacionAfectadaId"));

                    b.Property<int>("CantidadBarcos")
                        .HasColumnType("int");

                    b.Property<int>("CantidadBotes")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFragatas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadLanchas")
                        .HasColumnType("int");

                    b.Property<bool>("Intervinientes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Otro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("EmbarcacionAfectadaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("EmbarcacionesAfectadas");
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int?>("Año")
                        .HasColumnType("int");

                    b.Property<int>("Discriminador")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Patente")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("VehiculoId");

                    b.ToTable("Vehiculo");

                    b.HasDiscriminator<int>("Discriminador");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Data.Models.Imagenes.CertificadoMedico", b =>
                {
                    b.HasBaseType("Core.Data.Models.Imagenes.Imagen");

                    b.Property<int>("LicenciaId")
                        .HasColumnType("int");

                    b.HasIndex("LicenciaId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Core.Data.Models.Imagenes.Imagen_Personal", b =>
                {
                    b.HasBaseType("Core.Data.Models.Imagenes.Imagen");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Core.Data.Models.Imagenes.Imagen_VehiculoSalida", b =>
                {
                    b.HasBaseType("Core.Data.Models.Imagenes.Imagen");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasIndex("VehiculoId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Personal", b =>
                {
                    b.HasBaseType("Core.Data.Models.Personas.Persona");

                    b.Property<Guid>("EntraId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GrupoSanguineo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LugarNacimiento")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UPN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasIndex("EntraId")
                        .IsUnique();
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.SeguroVehiculo", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Componentes.Seguro");

                    b.Property<DateTime?>("FechaDeVencimineto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroDePoliza")
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasIndex("VehiculoId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.SeguroVivienda", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Componentes.Seguro");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Accidente", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("CondicionesClimaticas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroCondicion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Accidente_Tipo");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.FactorClimatico", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int>("CantidadAfectadaFactorClimatico")
                        .HasColumnType("int");

                    b.Property<string>("Evacuacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Superficie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Evacuacion")
                                .HasColumnName("FactorClimatico_Evacuacion");

                            t.Property("Tipo")
                                .HasColumnName("FactorClimatico_Tipo");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.Incendio", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int?>("CantidadAmbientes")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadPisos")
                        .HasColumnType("int");

                    b.Property<string>("DetalleSuperficieAfectadaIncendio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("DeteccionAutomatica")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Extintor")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Hidrante")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreEstablecimiento")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtraAbertura")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroLugarIncendio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroTecho")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PisoAfectado")
                        .HasColumnType("int");

                    b.Property<string>("SuperficieAfectadaCausa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoAbertura")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoEvacuacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoSuperficieAfectada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoTecho")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(15);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.MaterialPeligroso", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int>("CantidadAfectadaMaterialPeligroso")
                        .HasColumnType("int");

                    b.Property<bool>("Confinamiento")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Controlada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Descontaminacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DetallesAccionesMateriales")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DetallesAccionesPersonas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("DilucionDeVapores")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Evacuacion")
                        .HasColumnType("int");

                    b.Property<bool>("Neutralizacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OtraAccionesMateriales")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OtraAccionesPersonas")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SinAccion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sustancias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoSituacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoSuperficie")
                        .HasColumnType("int");

                    b.Property<bool>("Trasvase")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Venteo")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.RescateAnimal", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("LugarRescateAnimal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroLugarRescate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.RescatePersona", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("LugarRescatePersona")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroLugarRescate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("TipoOrganizacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Componentes.MovimientoCambioCuota", b =>
                {
                    b.HasBaseType("Core.Data.Models.Socios.Componentes.MovimientoSocio");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenciaDePago")
                        .HasColumnType("int");

                    b.Property<double>("Monto")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("MovimientoCambioCuota");
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Componentes.MovimientoCambioEstado", b =>
                {
                    b.HasBaseType("Core.Data.Models.Socios.Componentes.MovimientoSocio");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MovimientoCambioEstado");
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Componentes.Pagos.PagoEfectivo", b =>
                {
                    b.HasBaseType("Core.Data.Models.Socios.Componentes.Pagos.PagoSocio");

                    b.Property<int>("CobradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntregaAComision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.HasIndex("CobradorId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.VehiculoAfectado", b =>
                {
                    b.HasBaseType("Core.Data.Models.Vehiculos.Vehiculo");

                    b.Property<bool>("Airbag")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Color")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreYApellidoDuenio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<bool>("SeConoceConductor")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SeguroId")
                        .HasColumnType("int");

                    b.HasIndex("SeguroId")
                        .IsUnique();

                    b.ToTable("Vehiculo", t =>
                        {
                            t.Property("Observaciones")
                                .HasColumnName("VehiculoAfectado_Observaciones");
                        });

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Flota.VehiculoSalida", b =>
                {
                    b.HasBaseType("Core.Data.Models.Vehiculos.Vehiculo");

                    b.Property<string>("Combustible")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaProximoService")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimoService")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ImagenId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroMovil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.HasIndex("EncargadoId");

                    b.HasIndex("ImagenId")
                        .IsUnique();
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Vehiculo_Personal", b =>
                {
                    b.HasBaseType("Core.Data.Models.Vehiculos.Vehiculo");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.HasIndex("PersonalId");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Bombero", b =>
                {
                    b.HasBaseType("Core.Data.Models.Personas.Personal.Personal");

                    b.Property<int?>("Altura")
                        .HasColumnType("int");

                    b.Property<bool>("Chofer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Dotacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<string>("NivelEstudios")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroIoma")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumeroLegajo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<int?>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Profesion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("VencimientoRegistro")
                        .HasColumnType("datetime(6)");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.HasIndex("NumeroLegajo")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Cobrador", b =>
                {
                    b.HasBaseType("Core.Data.Models.Personas.Personal.Personal");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("ZonasAsignadas")
                        .HasColumnType("int");

                    b.ToTable("Persona", t =>
                        {
                            t.Property("Estado")
                                .HasColumnName("Cobrador_Estado");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.ComisionDirectiva", b =>
                {
                    b.HasBaseType("Core.Data.Models.Personas.Personal.Personal");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Persona", t =>
                        {
                            t.Property("Estado")
                                .HasColumnName("ComisionDirectiva_Estado");

                            t.Property("Grado")
                                .HasColumnName("ComisionDirectiva_Grado");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.IncendioAeronaves", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Incendios.Incendio");

                    b.Property<int>("TipoAeronave")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(17);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.IncendioComercio", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Incendios.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.IncendioEstablecimientoEducativo", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Incendios.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("TipoLugar")
                                .HasColumnName("IncendioEstablecimientoEducativo_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.IncendioEstablecimientoPublico", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Incendios.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("TipoLugar")
                                .HasColumnName("IncendioEstablecimientoPublico_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(9);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.IncendioForestal", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Incendios.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("TipoLugar")
                                .HasColumnName("IncendioForestal_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(10);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.IncendioHospitalesYClinicas", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Incendios.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("TipoLugar")
                                .HasColumnName("IncendioHospitalesYClinicas_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(11);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.IncendioIndustria", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Incendios.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("TipoLugar")
                                .HasColumnName("IncendioIndustria_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(12);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Incendios.IncendioVivienda", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Incendios.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("TipoLugar")
                                .HasColumnName("IncendioVivienda_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(13);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.ServicioEspecialColaboraciónFuerzasSeguridad", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial");

                    b.Property<string>("DetallesColaboFuerzasSeguridad")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(23);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecialCapacitacion", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial");

                    b.Property<DateTime>("DiaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NivelDeCapacitacion")
                        .HasColumnType("int");

                    b.Property<string>("NivelDeCapacitacionOtro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoCapacitacion")
                        .HasColumnType("int");

                    b.Property<string>("TipoCapacitacionOtra")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(18);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecialColocaciónDriza", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial");

                    b.Property<string>("Detalles")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreEstablecimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("NombreEstablecimiento")
                                .HasColumnName("ServicioEspecialColocaciónDriza_NombreEstablecimiento");

                            t.Property("TipoLugar")
                                .HasColumnName("ServicioEspecialColocaciónDriza_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(19);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecialFalsaAlarma", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Detalles")
                                .HasColumnName("ServicioEspecialFalsaAlarma_Detalles");
                        });

                    b.HasDiscriminator().HasValue(21);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecialPrevencion", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial");

                    b.Property<string>("TipoPrevencion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(14);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecialRepresentacion", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial");

                    b.Property<string>("TipoRepresentacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecialRetiradoDeObito", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial");

                    b.Property<string>("DetallesObito")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(22);
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecialSuministroAgua", b =>
                {
                    b.HasBaseType("Core.Data.Models.Salidas.Planillas.Servicios.ServicioEspecial");

                    b.Property<string>("DetallesSuministroAgua")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreEstablecimientoSuministroAgua")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(20);
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Flota.Embarcacion", b =>
                {
                    b.HasBaseType("Core.Data.Models.Vehiculos.Flota.VehiculoSalida");

                    b.HasIndex("NumeroMovil")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Flota.Movil", b =>
                {
                    b.HasBaseType("Core.Data.Models.Vehiculos.Flota.VehiculoSalida");

                    b.Property<string>("CajaVelocidades")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CantidadAceite")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadLitros")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltCambioBateria")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("LibrasCubiertas")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MarcaAceite")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MarcaBateria")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MedidasCubiertas")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModeloBomba")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModeloFiltroAire")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroChasis")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TensionCElectrico")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoAceite")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoDireccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.HasIndex("NumeroMovil")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Brigadas.Bombero_Brigada", b =>
                {
                    b.HasOne("Core.Data.Models.Grupos.Brigadas.Brigada", "Brigada")
                        .WithMany("Bomberos")
                        .HasForeignKey("BrigadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Bombero")
                        .WithMany("Brigadas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Brigada");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Brigadas.Brigada", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Encargado")
                        .WithMany()
                        .HasForeignKey("EncargadoPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encargado");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.Bombero_Dependencia", b =>
                {
                    b.HasOne("Core.Data.Models.Grupos.Dependencias.Dependencia", "Dependencia")
                        .WithMany("Bomberos")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Bombero")
                        .WithMany("Dependencias")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.Dependencia", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Encargado")
                        .WithMany()
                        .HasForeignKey("EncargadoPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encargado");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.EquiposAutonomos.Movimiento_EquipoAutonomo", b =>
                {
                    b.HasOne("Core.Data.Models.Grupos.Dependencias.Dependencia", "DependenciaDestino")
                        .WithMany()
                        .HasForeignKey("DependenciaDestinoId");

                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Encargado")
                        .WithMany()
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Grupos.Dependencias.EquiposAutonomos.EquipoAutonomo", "EquipoAutonomo")
                        .WithMany("Movimientos")
                        .HasForeignKey("EquipoAutonomoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Vehiculos.Flota.VehiculoSalida", "VehiculoDestino")
                        .WithMany()
                        .HasForeignKey("VehiculoDestinoId");

                    b.Navigation("DependenciaDestino");

                    b.Navigation("Encargado");

                    b.Navigation("EquipoAutonomo");

                    b.Navigation("VehiculoDestino");
                });

            modelBuilder.Entity("Core.Data.Models.Objetos.Componentes.MovimientoMaterial", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "DestinoBombero")
                        .WithMany("DestinoMaterial")
                        .HasForeignKey("DestinoBomberoPersonaId");

                    b.HasOne("Core.Data.Models.Vehiculos.Flota.Movil", "DestinoMovil")
                        .WithMany()
                        .HasForeignKey("DestinoMovilVehiculoId");

                    b.HasOne("Core.Data.Models.Objetos.Material", "Materiales")
                        .WithMany()
                        .HasForeignKey("MaterialesMaterialId");

                    b.Navigation("DestinoBombero");

                    b.Navigation("DestinoMovil");

                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Damnificado_Salida", b =>
                {
                    b.HasOne("Core.Data.Models.Salidas.Componentes.FuerzaInterviniente_Salida", "FuerzaInterviniente")
                        .WithMany("Damnificados")
                        .HasForeignKey("FuerzaIntervinienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("Damnificados")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuerzaInterviniente");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Componentes.AscensoBombero", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "PersonalAfectado")
                        .WithMany("Ascensos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalAfectado");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Componentes.Contacto", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Personal", "Persona")
                        .WithOne("Contacto")
                        .HasForeignKey("Core.Data.Models.Personas.Personal.Componentes.Contacto", "PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Componentes.Licencia", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "BomberoAfectado")
                        .WithMany("Licencias")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BomberoAfectado");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Componentes.Sancion", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "PersonalSancionado")
                        .WithMany("SancionesRecibidas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalSancionado");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.BomberoSalida", b =>
                {
                    b.HasOne("Core.Data.Models.Vehiculos.Flota.Movil", "MovilAsignado")
                        .WithMany()
                        .HasForeignKey("MovilId");

                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Bombero")
                        .WithMany("Salidas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("CuerpoParticipante")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("MovilAsignado");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.FuerzaInterviniente_Salida", b =>
                {
                    b.HasOne("Core.Data.Models.Grupos.FuerzasIntervinientes.FuerzaInterviniente", "Fuerzainterviniente")
                        .WithMany()
                        .HasForeignKey("FuerzaIntervinienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("FuerzasIntervinientes")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuerzainterviniente");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.Movil_Salida", b =>
                {
                    b.HasOne("Core.Data.Models.Vehiculos.Flota.Movil", "Movil")
                        .WithMany("Salidas")
                        .HasForeignKey("MovilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Chofer")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("Moviles")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chofer");

                    b.Navigation("Movil");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.OcupanteVehiculo", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Damnificado_Salida", "Damnificado")
                        .WithOne("OcupanteInfo")
                        .HasForeignKey("Core.Data.Models.Salidas.Componentes.OcupanteVehiculo", "DamnificadoSalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Salidas.Componentes.VehiculoAfectado", "VehiculoAfectado")
                        .WithMany("Ocupantes")
                        .HasForeignKey("VehiculoAfectadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Damnificado");

                    b.Navigation("VehiculoAfectado");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Encargado")
                        .WithMany()
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "QuienLleno")
                        .WithMany()
                        .HasForeignKey("QuienLlenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Models.Salidas.Componentes.SeguroVivienda", "Seguro")
                        .WithOne("Salida")
                        .HasForeignKey("Core.Data.Models.Salidas.Planillas.Salida", "SeguroId");

                    b.Navigation("Encargado");

                    b.Navigation("QuienLleno");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Componentes.MovimientoSocio", b =>
                {
                    b.HasOne("Core.Data.Models.Socios.Socio", "Socio")
                        .WithMany("Historial")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Componentes.Pagos.PagoSocio", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.ComisionDirectiva", "ConfirmadoPor")
                        .WithMany()
                        .HasForeignKey("ConfirmadoPorPersonaId");

                    b.HasOne("Core.Data.Models.Socios.Socio", "Socio")
                        .WithMany("Pagos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmadoPor");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Flota.EmbarcacionAfectada", b =>
                {
                    b.HasOne("Core.Data.Models.Salidas.Planillas.Incendios.Incendio", "Incendio")
                        .WithMany()
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incendio");
                });

            modelBuilder.Entity("Core.Data.Models.Imagenes.CertificadoMedico", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Componentes.Licencia", "Licencia")
                        .WithMany()
                        .HasForeignKey("LicenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licencia");
                });

            modelBuilder.Entity("Core.Data.Models.Imagenes.Imagen_Personal", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Personal", "Personal")
                        .WithOne("Imagen")
                        .HasForeignKey("Core.Data.Models.Imagenes.Imagen_Personal", "PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.SeguroVehiculo", b =>
                {
                    b.HasOne("Core.Data.Models.Salidas.Componentes.VehiculoAfectado", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Componentes.Pagos.PagoEfectivo", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Cobrador", "Cobrador")
                        .WithMany()
                        .HasForeignKey("CobradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobrador");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.VehiculoAfectado", b =>
                {
                    b.HasOne("Core.Data.Models.Salidas.Componentes.SeguroVehiculo", "Seguro")
                        .WithOne()
                        .HasForeignKey("Core.Data.Models.Salidas.Componentes.VehiculoAfectado", "SeguroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Flota.VehiculoSalida", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Bombero", "Encargado")
                        .WithMany("VehiculosEncargado")
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Data.Models.Imagenes.Imagen_VehiculoSalida", "Imagen")
                        .WithOne("Vehiculo")
                        .HasForeignKey("Core.Data.Models.Vehiculos.Flota.VehiculoSalida", "ImagenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Encargado");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Vehiculo_Personal", b =>
                {
                    b.HasOne("Core.Data.Models.Personas.Personal.Personal", "Personal")
                        .WithMany("VehiculosPersonales")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Bombero", b =>
                {
                    b.HasOne("Core.Data.Models.Grupos.Dependencias.Comunicaciones.Comunicacion", "Handie")
                        .WithOne("Bombero")
                        .HasForeignKey("Core.Data.Models.Personas.Personal.Bombero", "EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Handie");
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Flota.Movil", b =>
                {
                    b.HasOne("Core.Data.Models.Grupos.Dependencias.Comunicaciones.Comunicacion", "HandieMovil")
                        .WithOne("Movil")
                        .HasForeignKey("Core.Data.Models.Vehiculos.Flota.Movil", "EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HandieMovil");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Brigadas.Brigada", b =>
                {
                    b.Navigation("Bomberos");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.Comunicaciones.Comunicacion", b =>
                {
                    b.Navigation("Bombero");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.Dependencia", b =>
                {
                    b.Navigation("Bomberos");
                });

            modelBuilder.Entity("Core.Data.Models.Grupos.Dependencias.EquiposAutonomos.EquipoAutonomo", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Damnificado_Salida", b =>
                {
                    b.Navigation("OcupanteInfo");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.FuerzaInterviniente_Salida", b =>
                {
                    b.Navigation("Damnificados");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.Navigation("CuerpoParticipante");

                    b.Navigation("Damnificados");

                    b.Navigation("FuerzasIntervinientes");

                    b.Navigation("Moviles");
                });

            modelBuilder.Entity("Core.Data.Models.Socios.Socio", b =>
                {
                    b.Navigation("Historial");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Core.Data.Models.Imagenes.Imagen_VehiculoSalida", b =>
                {
                    b.Navigation("Vehiculo")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Personal", b =>
                {
                    b.Navigation("Contacto");

                    b.Navigation("Imagen");

                    b.Navigation("VehiculosPersonales");
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.SeguroVivienda", b =>
                {
                    b.Navigation("Salida")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Data.Models.Salidas.Componentes.VehiculoAfectado", b =>
                {
                    b.Navigation("Ocupantes");
                });

            modelBuilder.Entity("Core.Data.Models.Personas.Personal.Bombero", b =>
                {
                    b.Navigation("Ascensos");

                    b.Navigation("Brigadas");

                    b.Navigation("Dependencias");

                    b.Navigation("DestinoMaterial");

                    b.Navigation("Licencias");

                    b.Navigation("Salidas");

                    b.Navigation("SancionesRecibidas");

                    b.Navigation("VehiculosEncargado");
                });

            modelBuilder.Entity("Core.Data.Models.Vehiculos.Flota.Movil", b =>
                {
                    b.Navigation("Salidas");
                });
#pragma warning restore 612, 618
        }
    }
}
