// <auto-generated />
using System;
using Vista.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Vista.Data.Migrations
{
    [DbContext(typeof(BomberosDbContext))]
    partial class BomberosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.BomberoDependencia", b =>
                {
                    b.Property<int>("BomberoDependenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("BomberoDependenciaId");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("BomberoDependencia");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.BomberoSalida", b =>
                {
                    b.Property<int>("BomberoSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<bool>("Salio")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BomberoSalidaId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("BomberoSalida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Contacto", b =>
                {
                    b.Property<int>("ContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TelefonoFijo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TelefonoLaboral")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ContactoId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Dependencia", b =>
                {
                    b.Property<int>("DependenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NombreDependencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DependenciaId");

                    b.ToTable("Dependencia");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.MovilBombero", b =>
                {
                    b.Property<int>("MovilBomberoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("MovilBomberoId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("VehiculoId", "PersonaId");

                    b.ToTable("MovilBombero");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.MovilSalida", b =>
                {
                    b.Property<int>("MovilSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CargoCombustible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MovilId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("MovilSalidaId");

                    b.HasIndex("MovilId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("MovilSalida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LugarNacimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NivelEstudios")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroIoma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Profesion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas", (string)null);

                    b.HasDiscriminator<int>("TipoPersona").HasValue(2);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SeguroId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.HasKey("VehiculoId");

                    b.HasIndex("SeguroId")
                        .IsUnique();

                    b.ToTable("Vehiculo");

                    b.HasDiscriminator<int>("TipoVehiculo");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.Property<int>("DamnificadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LugarDeNacimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DamnificadoId");

                    b.HasIndex("SalidaId");

                    b.ToTable("Damnificados");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.DatosCapacitacion", b =>
                {
                    b.Property<int>("DatosCapacitacionId")
                        .HasColumnType("int");

                    b.Property<string>("CapacitacionOtra")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiasCapacitacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HorariosCapacitacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NivelCapacitacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NivelCapacitacionOtro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoCapacitacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DatosCapacitacionId");

                    b.ToTable("DatosCapacitaciones");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.EmbarcacionAfectada", b =>
                {
                    b.Property<int>("EmbarcacionAfectadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadBarcos")
                        .HasColumnType("int");

                    b.Property<int>("CantidadBotes")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFragatas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadLanchas")
                        .HasColumnType("int");

                    b.Property<bool>("Intervinientes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Otro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("EmbarcacionAfectadaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("EmbarcacionesAfectadas");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Incidente", b =>
                {
                    b.Property<int>("IncidenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MovilVehiculoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("IncidenteId");

                    b.HasIndex("MovilVehiculoId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Incidente");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Incidente");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Seguro", b =>
                {
                    b.Property<int>("SeguroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompañiaAseguradora")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaDeVencimineto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroDePoliza")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SeguroId");

                    b.ToTable("Seguros");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Seguro");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.Property<int>("SalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApellidoSolicitante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CalleORuta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Depto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DniSolicitante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<string>("EntreCalles")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("HoraLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KmLlegada")
                        .HasColumnType("int");

                    b.Property<int>("KmSalida")
                        .HasColumnType("int");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroOKilometro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumeroParte")
                        .HasColumnType("int");

                    b.Property<string>("PisoNumero")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuienLlenoId")
                        .HasColumnType("int");

                    b.Property<string>("Receptor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ReceptorId")
                        .HasColumnType("int");

                    b.Property<int?>("SeguroId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoSolicitante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoSalida")
                        .HasColumnType("int");

                    b.Property<string>("TipoZona")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SalidaId");

                    b.HasIndex("EncargadoId");

                    b.HasIndex("QuienLlenoId");

                    b.HasIndex("ReceptorId");

                    b.HasIndex("SeguroId")
                        .IsUnique();

                    b.ToTable("Salidas", (string)null);

                    b.HasDiscriminator<int>("TipoSalida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Bombero", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Persona");

                    b.Property<string>("Brigada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Chofer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Dotacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("FechaAceptacion")
                        .HasColumnType("date");

                    b.Property<string>("FotoBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumeroLegajo")
                        .HasColumnType("int");

                    b.Property<string>("Resolucion1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Resolucion2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Resolucion3")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Resolucion4")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Resolucion5")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Resolucion6")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("VencimientoRegistro")
                        .HasColumnType("date");

                    b.HasIndex("NumeroLegajo")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Movil", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Vehiculo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FotoBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroChasis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroMotor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroMovil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasIndex("NumeroMovil")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.VehiculoPersonal", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Vehiculo");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasIndex("PersonaId");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.IncidenteDependencia", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Componentes.Incidente");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("int");

                    b.HasIndex("DependenciaId");

                    b.HasDiscriminator().HasValue("IncidenteDependencia");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.SeguroSalida", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Componentes.Seguro");

                    b.HasDiscriminator().HasValue("SeguroSalida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.SeguroVehiculo", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Componentes.Seguro");

                    b.HasDiscriminator().HasValue("SeguroVehiculo");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectado", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Vehiculo");

                    b.Property<bool?>("Airbag")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IncendioSalidaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasIndex("IncendioSalidaId");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoDamnificado", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Vehiculo");

                    b.Property<bool?>("Airbag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("VehiculoDamnificado_Airbag");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DamnificadoId")
                        .HasColumnType("int");

                    b.HasIndex("DamnificadoId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Accidente", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int>("CantidadVehiculos")
                        .HasColumnType("int");

                    b.Property<string>("CondicionesClimaticas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroCondicion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Accidente_Tipo");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.FactorClimatico", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("DetalleSuperficieDañada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Evacuacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FactorClimatico_Evacuacion");

                    b.Property<string>("Superficie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FactorClimatico_Tipo");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int?>("CantidadAmbientes")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadPisos")
                        .HasColumnType("int");

                    b.Property<string>("DetalleSuperficieAfectadaIncendio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("DeteccionAutomaticaId")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Extintor")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Hidrante")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreEstablecimiento")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtraAbertura")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroLugarDeSiniestroEmbarcacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroTecho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PisoAfectado")
                        .HasColumnType("int");

                    b.Property<string>("SuperficieAfectadaCausa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Incendio_Tipo");

                    b.Property<string>("TipoAbertura")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoEvacuacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoLugarSiniestroEmbarcacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoSuperficieAfectada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoTecho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(15);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.MaterialPeligroso", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<bool>("Confinamiento")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Controlada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Descontaminacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DetalleSuperficieAfectada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DetallesAccionesMateriales")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DetallesAccionesPersonas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("DilucionDeVapores")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Evacuacion")
                        .HasColumnType("int");

                    b.Property<bool>("Neutralizacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OtraAccionesMateriales")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OtraAccionesPersonas")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SinAccion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sustancias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoSituacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoSuperficie")
                        .HasColumnType("int");

                    b.Property<bool>("Trasvase")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Venteo")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.RescateAnimal", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("Otro")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoRescateAnimal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.RescatePersona", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("Otro")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoRescatePersona")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("OtroRepresentacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ServicioEspecial_Tipo");

                    b.Property<string>("TipoOrganizacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(16);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectadoAccidente", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectado");

                    b.HasIndex("SalidaId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectadoIncendio", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectado");

                    b.HasIndex("SalidaId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioComercio", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioEstablecimientoEducativo", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IncendioEstablecimientoEducativo_TipoLugar");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioEstablecimientoPublico", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IncendioEstablecimientoPublico_TipoLugar");

                    b.HasDiscriminator().HasValue(9);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioForestal", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IncendioForestal_TipoLugar");

                    b.HasDiscriminator().HasValue(10);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioHospitalesYClinicas", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IncendioHospitalesYClinicas_TipoLugar");

                    b.HasDiscriminator().HasValue(11);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioIndustria", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IncendioIndustria_TipoLugar");

                    b.HasDiscriminator().HasValue(12);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioVivienda", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IncendioVivienda_TipoLugar");

                    b.HasDiscriminator().HasValue(13);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecialPrevencion", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<string>("TipoPrevencion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(14);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecialRepresentacion", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<string>("TipoRepresentacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.BomberoDependencia", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Dependencia", "Dependencia")
                        .WithMany("Bomberos")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Bombero")
                        .WithOne("Dependencia")
                        .HasForeignKey("BlazorApp1.Data.Models.Personales.BomberoDependencia", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.BomberoSalida", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Bombero")
                        .WithMany("Salidas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("CuerpoParticipante")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Contacto", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Persona", "Persona")
                        .WithOne("Contacto")
                        .HasForeignKey("BlazorApp1.Data.Models.Personales.Contacto", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.MovilBombero", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Bombero")
                        .WithOne("Movil")
                        .HasForeignKey("BlazorApp1.Data.Models.Personales.MovilBombero", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Movil", "Movil")
                        .WithMany("Bomberos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.MovilSalida", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Movil", "Movil")
                        .WithMany("Salidas")
                        .HasForeignKey("MovilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Chofer")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("Moviles")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chofer");

                    b.Navigation("Movil");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Vehiculo", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Componentes.SeguroVehiculo", "Seguro")
                        .WithOne("Vehiculo")
                        .HasForeignKey("BlazorApp1.Data.Models.Personales.Vehiculo", "SeguroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("Damnificados")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.DatosCapacitacion", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial", "ServicioEspecial")
                        .WithOne("DatosCapacitacion")
                        .HasForeignKey("BlazorApp1.Data.Models.Salidas.Componentes.DatosCapacitacion", "DatosCapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicioEspecial");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.EmbarcacionAfectada", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", "Incendio")
                        .WithMany("EmbarcacionAfectadas")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incendio");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Incidente", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Movil", null)
                        .WithMany("Incidentes")
                        .HasForeignKey("MovilVehiculoId");

                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "QuienHizo")
                        .WithMany("Incidentes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuienHizo");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Encargado")
                        .WithMany()
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "QuienLleno")
                        .WithMany()
                        .HasForeignKey("QuienLlenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "ReceptorBombero")
                        .WithMany()
                        .HasForeignKey("ReceptorId");

                    b.HasOne("BlazorApp1.Data.Models.Salidas.Componentes.SeguroSalida", "Seguro")
                        .WithOne("Salida")
                        .HasForeignKey("BlazorApp1.Data.Models.Salidas.Planillas.Salida", "SeguroId");

                    b.Navigation("Encargado");

                    b.Navigation("QuienLleno");

                    b.Navigation("ReceptorBombero");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.VehiculoPersonal", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Bombero")
                        .WithMany("Vehiculos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.IncidenteDependencia", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Dependencia", "Dependencia")
                        .WithMany("Incidentes")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectado", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", null)
                        .WithMany("VehiculoAfectados")
                        .HasForeignKey("IncendioSalidaId");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoDamnificado", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Componentes.Damnificado", "Damnificado")
                        .WithOne("VehiculoDamnificado")
                        .HasForeignKey("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoDamnificado", "DamnificadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Damnificado");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectadoAccidente", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Accidente", "Accidente")
                        .WithMany("VehiculosAfectado")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accidente");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectadoIncendio", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", "Incendio")
                        .WithMany()
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incendio");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Dependencia", b =>
                {
                    b.Navigation("Bomberos");

                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Persona", b =>
                {
                    b.Navigation("Contacto")
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.Navigation("VehiculoDamnificado");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.Navigation("CuerpoParticipante");

                    b.Navigation("Damnificados");

                    b.Navigation("Moviles");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Bombero", b =>
                {
                    b.Navigation("Dependencia");

                    b.Navigation("Incidentes");

                    b.Navigation("Movil");

                    b.Navigation("Salidas");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Movil", b =>
                {
                    b.Navigation("Bomberos");

                    b.Navigation("Incidentes");

                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.SeguroSalida", b =>
                {
                    b.Navigation("Salida")
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.SeguroVehiculo", b =>
                {
                    b.Navigation("Vehiculo")
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Accidente", b =>
                {
                    b.Navigation("VehiculosAfectado");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", b =>
                {
                    b.Navigation("EmbarcacionAfectadas");

                    b.Navigation("VehiculoAfectados");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial", b =>
                {
                    b.Navigation("DatosCapacitacion");
                });
#pragma warning restore 612, 618
        }
    }
}
