// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Data.Migrations
{
    [DbContext(typeof(BomberosDbContext))]
    partial class BomberosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.BomberoSalida", b =>
                {
                    b.Property<int>("BomberoSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BomberoPersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<bool>("Salio")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BomberoSalidaId");

                    b.HasIndex("BomberoPersonaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("BomberoSalida", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Contacto", b =>
                {
                    b.Property<int>("ContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCel")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoFijo")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoLaboral")
                        .HasColumnType("longtext");

                    b.HasKey("ContactoId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Contactos", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.MovilBombero", b =>
                {
                    b.Property<int>("MovilBomberoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MovilId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("MovilBomberoId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("MovilId", "PersonaId");

                    b.ToTable("MovilBombero", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.MovilSalida", b =>
                {
                    b.Property<int>("MovilSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CargoCombustible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ChoferPersonaId")
                        .HasColumnType("int");

                    b.Property<int>("MovilId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("MovilSalidaId");

                    b.HasIndex("ChoferPersonaId");

                    b.HasIndex("MovilId");

                    b.HasIndex("SalidaId");

                    b.ToTable("MovilSalida", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LugarNacimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NivelEstudios")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroIoma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Profesion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas", (string)null);

                    b.HasDiscriminator<int>("TipoPersona").HasValue(2);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<int?>("BomberoPersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.HasKey("VehiculoId");

                    b.HasIndex("BomberoPersonaId");

                    b.ToTable("Vehiculo", (string)null);

                    b.HasDiscriminator<int>("TipoVehiculo");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.Property<int>("DamnificadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("LugarDeNacimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("DamnificadoId");

                    b.HasIndex("SalidaId");

                    b.ToTable("Damnificados", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.DatosCapacitacion", b =>
                {
                    b.Property<int>("DatosCapacitacionId")
                        .HasColumnType("int");

                    b.Property<string>("CapacitacionOtra")
                        .HasColumnType("longtext");

                    b.Property<string>("DiasCapacitacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HorariosCapacitacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NivelCapacitacion")
                        .HasColumnType("int");

                    b.Property<string>("NivelCapacitacionOtro")
                        .HasColumnType("longtext");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoCapacitacion")
                        .HasColumnType("int");

                    b.HasKey("DatosCapacitacionId");

                    b.ToTable("DatosCapacitaciones", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.EmbarcacionAfectada", b =>
                {
                    b.Property<int>("EmbarcacionAfectadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadBarcos")
                        .HasColumnType("int");

                    b.Property<int>("CantidadBotes")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFragatas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadLanchas")
                        .HasColumnType("int");

                    b.Property<int>("IncendioSalidaId")
                        .HasColumnType("int");

                    b.Property<bool>("Intervinientes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Otro")
                        .HasColumnType("longtext");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("EmbarcacionAfectadaId");

                    b.HasIndex("IncendioSalidaId");

                    b.ToTable("EmbarcacionesAfectadas", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Seguro", b =>
                {
                    b.Property<int>("SeguroId")
                        .HasColumnType("int");

                    b.Property<string>("CompañiaAseguradora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaDeVencimineto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroDePoliza")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SalidaId")
                        .HasColumnType("int");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("SeguroId");

                    b.HasIndex("VehiculoId")
                        .IsUnique();

                    b.ToTable("Seguros", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.Property<int>("SalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApellidoSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CalleORuta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Depto")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DniSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<string>("EntreCalles")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KmLlegada")
                        .HasColumnType("int");

                    b.Property<int>("KmSalida")
                        .HasColumnType("int");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroOKilometro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroParte")
                        .HasColumnType("int");

                    b.Property<string>("PisoNumero")
                        .HasColumnType("longtext");

                    b.Property<int>("QuienLlenoId")
                        .HasColumnType("int");

                    b.Property<string>("Receptor")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReceptorId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoSalida")
                        .HasColumnType("int");

                    b.Property<int>("TipoZona")
                        .HasColumnType("int");

                    b.HasKey("SalidaId");

                    b.HasIndex("EncargadoId");

                    b.HasIndex("QuienLlenoId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Salidas", (string)null);

                    b.HasDiscriminator<int>("TipoSalida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Bombero", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Persona");

                    b.Property<string>("Brigada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Chofer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Dotacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaAceptacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLegajo")
                        .HasColumnType("int");

                    b.Property<string>("Resolucion1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resolucion2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resolucion3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resolucion4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resolucion5")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resolucion6")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("VencimientoRegistro")
                        .HasColumnType("datetime(6)");

                    b.HasIndex("NumeroLegajo");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Movil", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Vehiculo");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("NumeroChasis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroMotor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroMovil")
                        .IsRequired()
                        .HasColumnType("longtext");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.VehiculoPersonal", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Vehiculo");

                    b.Property<int>("BomberoId")
                        .HasColumnType("int");

                    b.HasIndex("BomberoId");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectado", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Vehiculo");

                    b.Property<int?>("AccidenteSalidaId")
                        .HasColumnType("int");

                    b.Property<bool?>("Airbag")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IncendioSalidaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasIndex("AccidenteSalidaId");

                    b.HasIndex("IncendioSalidaId");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoDamnificado", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Personales.Vehiculo");

                    b.Property<bool?>("Airbag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("VehiculoDamnificado_Airbag");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DamnificadoId")
                        .HasColumnType("int");

                    b.HasIndex("DamnificadoId")
                        .IsUnique();
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Accidente", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int>("CantidadVehiculos")
                        .HasColumnType("int");

                    b.Property<string>("CondicionesClimaticas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Accidente_Tipo");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.FactorClimatico", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("DetalleSuperficieDañada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Evacuacion")
                        .HasColumnType("int")
                        .HasColumnName("FactorClimatico_Evacuacion");

                    b.Property<int>("Superficie")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("FactorClimatico_Tipo");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int?>("CantidadAmbientes")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadPisos")
                        .HasColumnType("int");

                    b.Property<string>("DetalleSuperficieAfectadaIncendio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DeteccionAutomaticaId")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Extintor")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Hidrante")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreEstablecimiento")
                        .HasColumnType("longtext");

                    b.Property<string>("OtraAbertura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtroLugar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtroLugarDeSiniestroEmbarcacion")
                        .HasColumnType("longtext");

                    b.Property<string>("OtroTecho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PisoAfectado")
                        .HasColumnType("int");

                    b.Property<int>("SuperficieAfectadaCausa")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Incendio_Tipo");

                    b.Property<int>("TipoAbertura")
                        .HasColumnType("int");

                    b.Property<int>("TipoEvacuacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoLugarSiniestroEmbarcacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoSuperficieAfectada")
                        .HasColumnType("int");

                    b.Property<int>("TipoTecho")
                        .HasColumnType("int");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.MaterialPeligroso", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<bool>("Confinamiento")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Controlada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Descontaminacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DetalleSuperficieAfectada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DetallesAccionesMateriales")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DetallesAccionesPersonas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DilucionDeVapores")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Evacuacion")
                        .HasColumnType("int");

                    b.Property<bool>("Neutralizacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OtraAccionesMateriales")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OtraAccionesPersonas")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SinAccion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sustancias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("TipoSituacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoSuperficie")
                        .HasColumnType("int");

                    b.Property<bool>("Trasvase")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Venteo")
                        .HasColumnType("tinyint(1)");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.RescateAnimal", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("Otro")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoRescateAnimal")
                        .HasColumnType("int");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.RescatePersona", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("Otro")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoRescatePersona")
                        .HasColumnType("int");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("OtroRepresentacion")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("ServicioEspecial_Tipo");

                    b.Property<int>("TipoOrganizacion")
                        .HasColumnType("int");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectadoAccidente", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectado");

                    b.HasIndex("SalidaId");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectadoIncendio", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectado");

                    b.HasIndex("SalidaId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioComercio", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<int>("TipoLugar")
                        .HasColumnType("int");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioEstablecimientoEducativo", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<int>("TipoLugar")
                        .HasColumnType("int")
                        .HasColumnName("IncendioEstablecimientoEducativo_TipoLugar");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioEstablecimientoPublico", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<int>("TipoLugar")
                        .HasColumnType("int")
                        .HasColumnName("IncendioEstablecimientoPublico_TipoLugar");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioForestal", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<int>("TipoLugar")
                        .HasColumnType("int")
                        .HasColumnName("IncendioForestal_TipoLugar");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioHospitalesYClinicas", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<int>("TipoLugar")
                        .HasColumnType("int")
                        .HasColumnName("IncendioHospitalesYClinicas_TipoLugar");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioIndustria", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<int>("TipoLugar")
                        .HasColumnType("int")
                        .HasColumnName("IncendioIndustria_TipoLugar");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.IncendioVivienda", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<int>("TipoLugar")
                        .HasColumnType("int")
                        .HasColumnName("IncendioVivienda_TipoLugar");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecialPrevencion", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<int>("TipoPrevencion")
                        .HasColumnType("int");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecialRepresentacion", b =>
                {
                    b.HasBaseType("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<int>("TipoRepresentacion")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.BomberoSalida", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Bombero")
                        .WithMany("Salidas")
                        .HasForeignKey("BomberoPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("CuerpoParticipante")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Contacto", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Persona", "Persona")
                        .WithOne("Contacto")
                        .HasForeignKey("BlazorApp1.Data.Models.Personales.Contacto", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.MovilBombero", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Movil", "Movil")
                        .WithMany("Bomberos")
                        .HasForeignKey("MovilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Bombero")
                        .WithOne("Movil")
                        .HasForeignKey("BlazorApp1.Data.Models.Personales.MovilBombero", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.MovilSalida", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Chofer")
                        .WithMany()
                        .HasForeignKey("ChoferPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Movil", "Movil")
                        .WithMany("Salidas")
                        .HasForeignKey("MovilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("Moviles")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chofer");

                    b.Navigation("Movil");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Vehiculo", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", null)
                        .WithMany("Vehiculos")
                        .HasForeignKey("BomberoPersonaId");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("Damnificados")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.DatosCapacitacion", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial", "ServicioEspecial")
                        .WithOne("DatosCapacitacion")
                        .HasForeignKey("BlazorApp1.Data.Models.Salidas.Componentes.DatosCapacitacion", "DatosCapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicioEspecial");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.EmbarcacionAfectada", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", "Incendio")
                        .WithMany("EmbarcacionAfectadas")
                        .HasForeignKey("IncendioSalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incendio");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Seguro", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithOne("Seguro")
                        .HasForeignKey("BlazorApp1.Data.Models.Salidas.Componentes.Seguro", "SeguroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Vehiculo", "Vehiculo")
                        .WithOne("Seguro")
                        .HasForeignKey("BlazorApp1.Data.Models.Salidas.Componentes.Seguro", "VehiculoId");

                    b.Navigation("Salida");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Encargado")
                        .WithMany()
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "QuienLleno")
                        .WithMany()
                        .HasForeignKey("QuienLlenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "ReceptorBombero")
                        .WithMany()
                        .HasForeignKey("ReceptorId");

                    b.Navigation("Encargado");

                    b.Navigation("QuienLleno");

                    b.Navigation("ReceptorBombero");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.VehiculoPersonal", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Personales.Bombero", "Bombero")
                        .WithMany()
                        .HasForeignKey("BomberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectado", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Accidente", null)
                        .WithMany("VehiculosAfectado")
                        .HasForeignKey("AccidenteSalidaId");

                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", null)
                        .WithMany("VehiculoAfectados")
                        .HasForeignKey("IncendioSalidaId");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoDamnificado", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Componentes.Damnificado", "Damnificado")
                        .WithOne("VehiculoDamnificado")
                        .HasForeignKey("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoDamnificado", "DamnificadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Damnificado");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectadoAccidente", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Accidente", "Accidente")
                        .WithMany()
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accidente");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.VehiculoAfectadoIncendio", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", "Incendio")
                        .WithMany()
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incendio");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Persona", b =>
                {
                    b.Navigation("Contacto")
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Vehiculo", b =>
                {
                    b.Navigation("Seguro")
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.Navigation("VehiculoDamnificado");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.Navigation("CuerpoParticipante");

                    b.Navigation("Damnificados");

                    b.Navigation("Moviles");

                    b.Navigation("Seguro")
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Bombero", b =>
                {
                    b.Navigation("Movil");

                    b.Navigation("Salidas");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Personales.Movil", b =>
                {
                    b.Navigation("Bomberos");

                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Accidente", b =>
                {
                    b.Navigation("VehiculosAfectado");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.Incendio", b =>
                {
                    b.Navigation("EmbarcacionAfectadas");

                    b.Navigation("VehiculoAfectados");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Salidas.Planillas.ServicioEspecial", b =>
                {
                    b.Navigation("DatosCapacitacion");
                });
#pragma warning restore 612, 618
        }
    }
}
